target-version = "py313"
line-length = 100

[lint]
select = ["E", "F", "N", "I", "S", "NPY", "PD", "UP", "D", "D212", "D402", "D417"]
ignore = ["D100", "D104", "D400"]

[lint.per-file-ignores]
"scripts.py" = ["S603", "S605", "S607", "D"]
"tests/**/test*.py" = ["S101", "D"]

[lint.isort]
lines-after-imports = 2

[lint.pydocstyle]
convention = "numpy"
